mapa_traducao = {
    'id.orig_p': 'porta_origem',
    'id.resp_p': 'porta_destino',
    'proto': 'protocolo',
    'service': 'servico',
    'flow_duration': 'duracao_fluxo',
    
    'fwd_pkts_tot': 'total_pacotes_env',
    'bwd_pkts_tot': 'total_pacotes_rec',
    'fwd_data_pkts_tot': 'total_pacotes_dados_env',
    'bwd_data_pkts_tot': 'total_pacotes_dados_rec',
    
    'fwd_pkts_per_sec': 'pacotes_env_por_seg',
    'bwd_pkts_per_sec': 'pacotes_rec_por_seg',
    'flow_pkts_per_sec': 'pacotes_fluxo_por_seg',
    'down_up_ratio': 'razao_down_up',
    
    'fwd_header_size_tot': 'tam_cabecalho_env_total',
    'fwd_header_size_min': 'tam_cabecalho_env_min',
    'fwd_header_size_max': 'tam_cabecalho_env_max',
    'bwd_header_size_tot': 'tam_cabecalho_rec_total',
    'bwd_header_size_min': 'tam_cabecalho_rec_min',
    'bwd_header_size_max': 'tam_cabecalho_rec_max',
    
    'flow_FIN_flag_count': 'contagem_flag_FIN',
    'flow_SYN_flag_count': 'contagem_flag_SYN',
    'flow_RST_flag_count': 'contagem_flag_RST',
    'fwd_PSH_flag_count': 'contagem_flag_PSH_env',
    'bwd_PSH_flag_count': 'contagem_flag_PSH_rec',
    'flow_ACK_flag_count': 'contagem_flag_ACK',
    'fwd_URG_flag_count': 'contagem_flag_URG_env',
    'bwd_URG_flag_count': 'contagem_flag_URG_rec',
    'flow_CWR_flag_count': 'contagem_flag_CWR',
    'flow_ECE_flag_count': 'contagem_flag_ECE',
    
    'fwd_pkts_payload.min': 'payload_env_min',
    'fwd_pkts_payload.max': 'payload_env_max',
    'fwd_pkts_payload.tot': 'payload_env_total',
    'fwd_pkts_payload.avg': 'payload_env_media',
    'fwd_pkts_payload.std': 'payload_env_desvio',
    
    'bwd_pkts_payload.min': 'payload_rec_min',
    'bwd_pkts_payload.max': 'payload_rec_max',
    'bwd_pkts_payload.tot': 'payload_rec_total',
    'bwd_pkts_payload.avg': 'payload_rec_media',
    'bwd_pkts_payload.std': 'payload_rec_desvio',
    
    'flow_pkts_payload.min': 'payload_fluxo_min',
    'flow_pkts_payload.max': 'payload_fluxo_max',
    'flow_pkts_payload.tot': 'payload_fluxo_total',
    'flow_pkts_payload.avg': 'payload_fluxo_media',
    'flow_pkts_payload.std': 'payload_fluxo_desvio',
    
    'fwd_iat.min': 'iat_env_min',
    'fwd_iat.max': 'iat_env_max',
    'fwd_iat.tot': 'iat_env_total',
    'fwd_iat.avg': 'iat_env_media',
    'fwd_iat.std': 'iat_env_desvio',
    
    'bwd_iat.min': 'iat_rec_min',
    'bwd_iat.max': 'iat_rec_max',
    'bwd_iat.tot': 'iat_rec_total',
    'bwd_iat.avg': 'iat_rec_media',
    'bwd_iat.std': 'iat_rec_desvio',
    
    'flow_iat.min': 'iat_fluxo_min',
    'flow_iat.max': 'iat_fluxo_max',
    'flow_iat.tot': 'iat_fluxo_total',
    'flow_iat.avg': 'iat_fluxo_media',
    'flow_iat.std': 'iat_fluxo_desvio',
    
    'flow_active.min': 'fluxo_ativo_min',
    'flow_active.max': 'fluxo_ativo_max',
    'flow_active.tot': 'fluxo_ativo_total',
    'flow_active.avg': 'fluxo_ativo_media',
    'flow_active.std': 'fluxo_ativo_desvio',
    'flow_idle.min': 'fluxo_ocioso_min',
    'flow_idle.max': 'fluxo_ocioso_max',
    'flow_idle.tot': 'fluxo_ocioso_total',
    'flow_idle.avg': 'fluxo_ocioso_media',
    'flow_idle.std': 'fluxo_ocioso_desvio',
    
    'fwd_subflow_pkts': 'subfluxo_pacotes_env',
    'bwd_subflow_pkts': 'subfluxo_pacotes_rec',
    'fwd_subflow_bytes': 'subfluxo_bytes_env',
    'bwd_subflow_bytes': 'subfluxo_bytes_rec',
    'fwd_bulk_bytes': 'bulk_bytes_env',
    'bwd_bulk_bytes': 'bulk_bytes_rec',
    
    'fwd_init_window_size': 'tam_janela_inic_env',
    'bwd_init_window_size': 'tam_janela_inic_rec',
    
    'Attack_type': 'tipo_ataque'
}